EXPERIMENT:
  NAME: ""
  TAG: "dhkd,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "DHKD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
  AUX_CLASSIFIER: True
  AUX_CLASSIFIER_LINEAR: False
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 180
  LR: 0.05
  LR_DECAY_STAGES: [90, 120, 150]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

